POST http://localhost:8080/events 
content-type: application/json 

{
    "name": "new test",
    "description": "test event",
    "location": "test location",
    "datetime": "2025-01-01T15:30:00.000Z",
    "user_id": 1
}   